version: "3.9"

services:
  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    expose:
      - 5432
    env_file:
      - .env

  app:
    container_name: app
    build: .
    volumes:
      - .:/home/appuser/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db_network
    env_file:
      - .env

networks:
  db_network:

volumes:
  db_data: